name: ChatGPT Pull Request comment trigger
on:
  issue_comment:                                     
    types: [created, edited ]
jobs:
  pr_commented:
    if: ${{ github.event.issue.pull_request && matches(github.event.comment.body, "globant-bot please review this") }}
    runs-on: [ubuntu-latest]
    steps:
      - run: echo Comentario de un PR
      - uses: actions/chatgpt_action@main
